# Generated by Django 4.1.6 on 2023-04-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0011_yard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedEwaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectedewastedumped_date', models.DateField(auto_now_add=True)),
                ('collectedewaste_weight', models.CharField(max_length=100)),
                ('yard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.yard')),
            ],
        ),
    ]
