# Generated by Django 4.1.6 on 2023-02-10 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_name', models.CharField(max_length=50)),
                ('technician_gender', models.CharField(max_length=50)),
                ('technician_contact', models.CharField(max_length=50)),
                ('technician_email', models.CharField(max_length=50)),
                ('technician_password', models.CharField(max_length=50)),
                ('technician_photo', models.FileField(upload_to='TechnicianDocs/')),
                ('technician_experience', models.CharField(max_length=100)),
                ('technician_address', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.category')),
            ],
        ),
    ]
