# Generated by Django 4.1.6 on 2023-03-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_servicebook'),
        ('Admin', '0005_technician'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignservicebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asb_status', models.IntegerField(default=0)),
                ('servicebooking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.servicebook')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.technician')),
            ],
        ),
    ]
