# Generated by Django 4.1.6 on 2023-03-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_ewastecollector'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EwasteCollector',
        ),
    ]
