# Generated by Django 4.1.6 on 2023-03-21 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_ewastebooking'),
        ('Admin', '0009_ewastecollector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignewastebooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aeb_status', models.IntegerField(default=0)),
                ('collector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.ewastecollector')),
                ('ewastebooking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.ewastebooking')),
            ],
        ),
    ]
