# Generated by Django 4.1.6 on 2023-04-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_assignewastebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yard_name', models.CharField(max_length=50)),
            ],
        ),
    ]
