# Generated by Django 4.1.6 on 2023-03-03 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0006_assignservicebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicebill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicebill_date', models.DateField(auto_now_add=True)),
                ('servicebill_amount', models.CharField(max_length=100)),
                ('servicebill_noofdays', models.CharField(max_length=100)),
                ('servicebill_details', models.CharField(max_length=200)),
                ('servicebill_additionaldetails', models.CharField(max_length=200)),
                ('servicebill_partamount', models.CharField(max_length=100)),
                ('assignedservicebooking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.assignservicebook')),
            ],
        ),
    ]
