# Generated by Django 4.1.6 on 2023-02-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=50)),
            ],
        ),
    ]
