# Generated by Django 4.1.6 on 2023-02-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='technician_id',
            new_name='technician',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='user_id',
            new_name='user',
        ),
    ]
