# Generated by Django 4.1.6 on 2023-03-01 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_admin_admin_name'),
        ('Admin', '0005_technician'),
        ('User', '0004_alter_complaint_technician_alter_complaint_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Servicebook_details', models.CharField(max_length=100)),
                ('Servicebook_address', models.CharField(max_length=100)),
                ('Servicebook_date', models.DateField(auto_now_add=True)),
                ('Servicebook_status', models.IntegerField(default=0)),
                ('payment_status', models.IntegerField(default=0)),
                ('complaint_reply', models.CharField(max_length=100)),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.technician')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.user')),
            ],
        ),
    ]
