# Generated by Django 4.1.6 on 2023-03-01 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_servicebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicebook',
        ),
    ]
