# Generated by Django 4.1.6 on 2023-03-20 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_admin_admin_name'),
        ('User', '0007_servicebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ewastebooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ewastebooking_details', models.CharField(max_length=50)),
                ('ewastebooking_date', models.DateField(auto_now_add=True)),
                ('ewastebooking_status', models.IntegerField(default=0)),
                ('ewastebooking_collectionpoint', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.user')),
            ],
        ),
    ]
